Make it a composer project so it can, you know, work...
pandaleague/ErrorCatalog pull request #1
Opened 2018-03-23 12:10 UTC by shauno

2018-03-23 12:32 UTC, Ed-leRoux requested changes

2018-03-23 12:32 UTC, Ed-leRoux commented on .gitignore
> +/vendor/
vendor*

2018-03-23 12:32 UTC, Ed-leRoux commented on src/ErrorCatalog.php
> +    public function __construct($namespace, $language = 'en-US')
`$this->language = $language`

2018-03-23 12:40 UTC, shauno commented on .gitignore
> +/vendor/
That's how the `composer init` command sets it, but ¯\_(ツ)_/¯

2018-03-23 12:43 UTC, shauno commented on .gitignore
> +/vendor/
Then should the `idea/` directory be the same: `.idea*`?
I think I prefer how it is now, you're trying to exclude the directory, you don't need a wildcard

2018-03-28 18:25 UTC, shauno commented on src/ErrorCatalog.php
> +    public function getItem($name)
What should this method return if it doesn't find the item?

2018-03-28 18:25 UTC, shauno commented on src/ErrorSpecIssue.php
> +    protected $jsonPointer;
It's not really a json pointer though is it? What exactly is this extra identifier?

2018-04-03 06:33 UTC, Ed-leRoux requested changes

2018-04-03 06:33 UTC, Ed-leRoux commented on .gitignore
> +/vendor/
👍

2018-04-03 06:33 UTC, Ed-leRoux commented on src/ErrorSpecIssue.php
> +    protected $jsonPointer;
Maybe call this `reference`

2018-04-03 06:33 UTC, Ed-leRoux commented on src/ErrorCatalog.php
> +    public function getItem($name)
for now, `return null;`. Maybe we should add a default at a later stage

2018-04-03 07:20 UTC, Ed-leRoux approved these changes
👍

2018-04-03 07:21 UTC, merged